import { signal, effect } from "@preact/signals-core";
import * as anime from "animejs";
import { debounce, isNotNil } from "es-toolkit";
import AnyTouch from "any-touch";

// Optional controller returned by user-provided Boxjs snippets.
// Today Slipst only calls onWheel, mainly for static/manual animation mode.
type BoxjsController = {
  onWheel?: (context: {
    anime: typeof anime;
    root: ShadowRoot;
    host: HTMLElement;
    box: BoxjsInfo;
    event: WheelEvent;
    deltaY: number;
  }) => void;
};

type BoxjsInfo = {
  // Zero-based DOM order of the widget among all Boxjs widgets.
  index: number;
  // Unique id generated by Typst and applied to the outer host element.
  id: string;
  // Widget category: "boxjs" by default, "animejs" for the Anime.js template.
  kind: string;
};

// Keep runtime state for each inline Boxjs widget created from Typst metadata.
const boxjsBoxes = new Map<
  HTMLElement,
  { root: ShadowRoot; controller: BoxjsController; info: BoxjsInfo }
>();

// Static mode disables slip navigation by wheel and sends wheel deltas to figures instead.
const staticMode = signal(false);

// Instantiate every .slipst-boxjs placeholder emitted by slipst.typ.
// Each widget is isolated in a ShadowRoot so its local CSS does not leak into the slide.
function initBoxjsBoxes() {
  document.querySelectorAll(".slipst-boxjs").forEach((host, index) => {
    if (!(host instanceof HTMLElement) || boxjsBoxes.has(host)) return;

    const root = host.attachShadow({ mode: "open" });
    const html = host.getAttribute("data-slipst-boxjs-html") ?? "";
    const css = host.getAttribute("data-slipst-boxjs-css") ?? "";
    const js = host.getAttribute("data-slipst-boxjs-js") ?? "";
    const info = {
      index,
      id: host.getAttribute("data-slipst-boxjs-id") ?? host.id,
      kind: host.getAttribute("data-slipst-boxjs-kind") ?? "boxjs",
    };

    root.innerHTML = `
      <style>
        :host {
          display: block;
          width: 100%;
          height: 100%;
          box-sizing: border-box;
          contain: layout paint;
        }
        ${css}
      </style>
      ${html}
    `;

    let controller: BoxjsController = {};
    try {
      // User snippets are stored as source text in data attributes and evaluated here.
      // Parameters passed to the snippet:
      // - anime: bundled Anime.js module;
      // - root: ShadowRoot containing the user's html/css;
      // - host: outer .slipst-boxjs element;
      // - box: metadata object with index, id, and kind.
      const setup = new Function("anime", "root", "host", "box", js) as (
        anime: typeof anime,
        root: ShadowRoot,
        host: HTMLElement,
        box: BoxjsInfo,
      ) => BoxjsController | void;
      controller = setup(anime, root, host, info) ?? {};
    } catch (error) {
      console.error("Slipst boxjs widget failed to initialize", error);
    }

    boxjsBoxes.set(host, { root, controller, info });
  });
}

// Only widgets inside the currently active slip/alter should receive runtime events.
function activeBoxjsBoxes() {
  return Array.from(boxjsBoxes.entries()).filter(([host]) => {
    const slip = host.closest(".slip");
    if (!(slip instanceof HTMLElement)) return false;

    const slipIndex = parseInt(slip.getAttribute("data-slip") ?? "0", 10);
    const alterIndex = parseInt(
      slip.getAttribute("data-slip-alter-idx") ?? "1",
      10,
    );

    // Previous slips can stay visible in Slipst, but they are not active.
    // Static-mode wheel events must only reach the current slip/alter.
    return (
      slipIndex === currentSlip.value && alterIndex === currentSlipAlter.value
    );
  });
}

// Forward a wheel event to active Boxjs widgets in static mode.
function sendWheelToBoxjsBoxes(event: WheelEvent) {
  const boxes = activeBoxjsBoxes();
  if (boxes.length === 0) return false;

  boxes.forEach(([host, box]) => {
    box.controller.onWheel?.({
      anime,
      root: box.root,
      host,
      box: box.info,
      event,
      deltaY: event.deltaY,
    });
  });
  return true;
}

// Typst may export direct SVG frames; make those responsive inside a slip.
document.querySelectorAll(".slip > svg").forEach((svg) => {
  if (svg instanceof SVGElement) {
    svg.style.width = "100%";
    svg.style.height = "auto";
  }
});

/**
 * Parse the hash in the URL to get the current slip index and alter index.
 * The hash should be in the format "#slip-alter".
 */
function parseHash() {
  const hashGroups = /^(?<slip>\d+)(?:-(?<alter>\d+))?/.exec(
    location.hash.slice(1),
  )?.groups;

  let slip = parseInt(hashGroups?.slip ?? "1", 10);
  if (isNaN(slip) || slip < 1) {
    slip = 1;
  }

  let alter = parseInt(hashGroups?.alter ?? "1", 10);
  if (isNaN(alter) || alter < 1) {
    alter = 1;
  }

  return { slip, alter };
}

const { slip: initialSlip, alter: initialAlter } = parseHash();

// Presentation state. Signals re-run the layout/visibility effects below when changed.
const currentSlip = signal(initialSlip);
const currentSlipAlter = signal(initialAlter);

// Persist navigation in the URL so refresh/share/back-to-position works.
effect(() => {
  let hash = `#${currentSlip.value}`;
  if (currentSlipAlter.value > 1) {
    hash += `-${currentSlipAlter.value}`;
  }
  if (location.hash !== hash) {
    history.replaceState(null, "", hash);
  }
});

// Accept manual URL hash changes and synchronize them back into signals.
window.addEventListener("hashchange", () => {
  const { slip, alter } = parseHash();
  if (slip !== currentSlip.value) {
    currentSlip.value = slip;
  }
  if (alter !== currentSlipAlter.value) {
    currentSlipAlter.value = alter;
  }
});

// Highest slip index generated by the Typst side.
const maxSlip = Array.from(document.querySelectorAll(".slip"))
  .map((slip) => {
    const attr = slip.getAttribute("data-slip");
    return attr !== null ? parseInt(attr, 10) : 0;
  })
  .reduce((a, b) => Math.max(a, b), 0);

/**
 * Map from slip index to number of alters.
 */
const slipAlters = new Map(
  Array.from(document.querySelectorAll(".slip")).map((slip) => {
    const attrSlip = slip.getAttribute("data-slip");
    const attrAlter = slip.getAttribute("data-slip-alter-num");
    const slipIndex = attrSlip !== null ? parseInt(attrSlip, 10) : 0;
    const alterNum = attrAlter !== null ? parseInt(attrAlter, 10) : 1;
    return [slipIndex, alterNum] as const;
  }),
);

/**
 * Go to the next slip or alter.
 */
function nextSlip() {
  const alterNum = slipAlters.get(currentSlip.value) ?? 1;
  if (currentSlipAlter.value < alterNum) {
    currentSlipAlter.value += 1;
  } else if (currentSlip.value < maxSlip) {
    currentSlip.value += 1;
    currentSlipAlter.value = 1;
  }
}

/**
 * Go to the previous slip or alter.
 */
function previousSlip() {
  if (currentSlipAlter.value > 1) {
    currentSlipAlter.value -= 1;
  } else if (currentSlip.value > 1) {
    currentSlip.value -= 1;
    const alterNum = slipAlters.get(currentSlip.value) ?? 1;
    currentSlipAlter.value = alterNum;
  }
}

const main = document.querySelector("main");

// Mouse wheels can emit many events; debounce keeps navigation to one step per gesture.
const navigateWheel = debounce(
  (event: WheelEvent) => (event.deltaY > 0 ? nextSlip() : previousSlip()),
  50,
  { edges: ["leading"] },
);
if (main) {
  // Click and keyboard controls are intentionally simple: most actions advance one step.
  main.addEventListener("click", nextSlip);
  main.addEventListener("auxclick", (event) => {
    if (event.button !== 1) return;
    event.preventDefault();
    staticMode.value = !staticMode.value;
  });
  main.addEventListener("mousedown", (event) => {
    if (event.button === 1) event.preventDefault();
  });
  main.addEventListener(
    "wheel",
    (event) => {
      if (staticMode.value) {
        sendWheelToBoxjsBoxes(event);
        event.preventDefault();
        return;
      }
      navigateWheel(event);
    },
    { passive: false },
  );

  // Touch gestures mirror keyboard/mouse navigation on mobile devices.
  const anyTouch = new AnyTouch(main);
  anyTouch.on("swipeup", nextSlip);
  anyTouch.on("swipeleft", nextSlip);
  anyTouch.on("swiperight", previousSlip);
  anyTouch.on("swipedown", previousSlip);
}

// Keyboard navigation for presenter remotes and common slideshow shortcuts.
document.addEventListener("keydown", (event) => {
  if (
    ["ArrowRight", "ArrowDown", "PageDown", " ", "Enter"].includes(event.key)
  ) {
    nextSlip();
  } else if (
    ["ArrowLeft", "ArrowUp", "PageUp", "Backspace"].includes(event.key)
  ) {
    previousSlip();
  }
});

initBoxjsBoxes();

// Toggle visibility of every generated slip layer.
// Previous slips keep only their final alter visible; current slip shows its active alter;
// future slips stay hidden until navigation reaches them.
effect(() => {
  document.querySelectorAll(".slip").forEach((slip) => {
    const attrSlip = slip.getAttribute("data-slip");
    const slipIndex = attrSlip !== null ? parseInt(attrSlip, 10) : 0;

    const attrAlter = slip.getAttribute("data-slip-alter-idx");
    const alterIdx = attrAlter !== null ? parseInt(attrAlter, 10) : 1;

    if (slip instanceof HTMLElement) {
      if (slipIndex < currentSlip.value) {
        // Previous slips, only show the last alter.
        if (alterIdx !== (slipAlters.get(slipIndex) ?? 1)) {
          slip.style.opacity = "0";
        } else {
          slip.style.opacity = "1";
        }
      } else if (slipIndex === currentSlip.value) {
        // Current slip, show the current alter.
        if (alterIdx === currentSlipAlter.value) {
          slip.style.opacity = "1";
        } else {
          slip.style.opacity = "0";
        }
      } else {
        // Future slips, hide all alters.
        slip.style.opacity = "0";
      }
    }
  });
});

// Move the vertical container according to the latest active #up action.
// Without #up, the deck stays aligned to the top; with #up, the target slip is brought up.
const layoutEffect = () => {
  // Find the nearest slip with a "data-slip-up" attribute, starting from the current slip and going upwards.
  let up = document
    .querySelector(`[data-slip="${currentSlip.value}"]`)
    ?.getAttribute("data-slip-up");
  let dy = document
    .querySelector(`[data-slip="${currentSlip.value}"]`)
    ?.getAttribute("data-slip-dy");

  for (let i = currentSlip.value - 1; i > 0; i--) {
    if (isNotNil(up)) break;
    up = document
      .querySelector(`[data-slip="${i}"]`)
      ?.getAttribute("data-slip-up");
    dy = document
      .querySelector(`[data-slip="${i}"]`)
      ?.getAttribute("data-slip-dy");
  }

  if (isNotNil(up)) {
    const anchors = document.querySelectorAll(`[data-slip="${up}"]`);
    const anchor = Array.from(anchors)
      .filter((anchor) => anchor instanceof HTMLElement)
      .filter(
        (anchor) => window.getComputedStyle(anchor).display !== "none",
      )[0];
    const container = document.getElementById("container");
    if (anchor instanceof HTMLElement && container instanceof HTMLElement) {
      if (isNotNil(dy)) {
        // dy allows scrolling to a point inside the target slip instead of its top edge.
        const dyValue = parseFloat(dy);
        container.style.top = `calc(${-anchor.offsetTop}px - ${dyValue} * var(--slip-1cm))`;
      } else {
        container.style.top = `${-anchor.offsetTop}px`;
      }
    }
  } else {
    const container = document.getElementById("container");
    if (container instanceof HTMLElement) {
      container.style.top = "0";
    }
  }
};
effect(layoutEffect);

// During resize, recompute layout instantly to avoid seeing an animated correction jump.
if (document.defaultView) {
  document.defaultView.addEventListener("resize", () => {
    document.documentElement.style.setProperty("--transition-duration", "0s");
    layoutEffect();
    setTimeout(() => {
      document.documentElement.style.setProperty(
        "--transition-duration",
        "0.5s",
      );
    }, 1);
  });
}
